version: '3.8'

services:
  flask-app:
    build: App/.
    container_name: flask-app
    ports:
      - "8000:8000"
    volumes:
      - ./flask-app-logs:/app/logs  
    networks:
      - app-net

  fluentbit:
    build: Monitoring/fluent-bit
    container_name: fluentbit
    volumes:
      - ./flask-app-logs:/logs:ro
    networks:
      - monitoring-net

  fluentd:
    build: Monitoring/fluentd
    container_name: fluentd
    ports:
      - "9001:9001"
    networks:
      - monitoring-net
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    container_name: elasticsearch
    networks:
      - monitoring-net
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false #disable security on dev

  kibana-dashboard:
    image: docker.elastic.co/kibana/kibana:7.17.28
    container_name: kibana
    networks:
      - monitoring-net
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

networks:
  monitoring-net:
  app-net:

